### ISSUE TITLE
Please update for new JSON API

### ISSUE THREAD

**Issue by blalor** [gocd-contrib/script-executor-task#14]
The Java API will no longer be supported come the January release of GoCD.

**Comment by arvindsv** [comment]
@blalor It looks like this plugin is already updated (looking at [this line](https://github.com/gocd-contrib/script-executor-task/blob/e603446e7af244a39cd6ac7db9a29a7a3c18c080/src/com/tw/go/plugin/task/GoPluginImpl.java#L62)). So, it should be ok. The list of plugins, that we know of, which will (currently) not work is in the [GoCD release notes](https://www.go.cd/releases/).

**Comment by blalor** [comment]
I'm so sorry; I could have sworn I looked through the code.  I didn't see this plugin on that list, but there are a few others (like the websocket notifier plugin) that are not listed and are not updated, so I didn't take that list to be canonical.  Thank you for confirming!

**Comment by arvindsv** [comment]
:) No worries. Even the websocket notifier plugin [seems to be updated](https://github.com/gocd-contrib/script-executor-task/issues/14#issuecomment-252656375). In fact, the notification plugin never had a Java-only API. It was message based from the beginning. So, there's nothing to deprecate at this time.
