### ISSUE TITLE
Unicode problems while saving script executor task

### ISSUE THREAD

**Issue by render1980** [gocd-contrib/script-executor-task#18]
I wrote some cyrillic symbols in Script Executor Task form (field 'Script'):

![image](https://user-images.githubusercontent.com/2079450/52622781-b1e75280-2ebb-11e9-9096-a870964db8bf.png)

Then I saved it. And after I opened form again, there is encoding problem what I've seen:

![image](https://user-images.githubusercontent.com/2079450/52622789-b7449d00-2ebb-11e9-89fb-e6fd9361142f.png)

1. Where is encoding broken (H2 db / web server)?
2. Is it possible to fix it?

**Comment by arvindsv** [comment]
@render1980 Can you see what it is saved as, in the config XML?

For the record, I tried with a normal custom command and inserted this unicode character `И` and saw that it was saved properly in the XML and was read back properly.

When you insert it, are you sure they're UTF-8 and not extended ASCII? For instance, when I do this:

```
$ echo -n 'И' | od -xc
0000000    98d0
          � 230
0000002
```

`d0 98` is the right UTF-8 encoding for that character, if you see [this](https://unicode-table.com/en/0418/). From a GoCD perspective, it should work if the input is UTF-8.
