### ISSUE TITLE
dependencies don't resolve when building with maven

### ISSUE THREAD

**Issue by jefftrimm** [gocd-contrib/script-executor-task#2]
Maven can't resolve http://repo.maven.apache.org/maven2/com/thoughtworks/go/go-plugin-api/14.4.0/go-plugin-api-14.4.0.jar

If there are non-standard maven repos that are needed, please include any repo declarations in the POM. Thanks!

**Comment by srinivasupadhya** [comment]
This is fixed now. go-plugin-api is available on maven central & i have updated the dependency appropriately.
