### ISSUE TITLE
Plugin doesn't show up in Go 14.40 ?

### ISSUE THREAD

**Issue by jefftrimm** [gocd-contrib/script-executor-task#3]
I put the script-executor-0.1.jar into /var/lib/go-server/plugins/external, restarted Go, and nothing new is showing up in the New Task UI to indicate a Script Executor is available?

**Comment by srinivasupadhya** [comment]
I have removed binaries from dist/ folder from all plugins I have written. They will now be available only in releases. Thanks for pointing that out.

**Comment by srilakshmitalla** [comment]
I downloaded the jar from  https://github.com/srinivasupadhya/script-executor-task/releases but it doesn't show up in my UI under plugins.
