### ISSUE TITLE
Environment Variables don't persist

### ISSUE THREAD

**Issue by ralfonso-directnic** [gocd-contrib/script-executor-task#32]
When using the plugin and setting a variable/exporting it 

export ABC=1

Environment variables that are exported aren't available in other jobs etc.  Looking at the code it appears that the environment is loaded but there is no provision to export out any environment change?  Or am I doing something wrong here, if so any workaround?

**Comment by arvindsv** [comment]
Jobs can run in parallel. And tasks are independent. So, those environment variables won't be available. You'll either need to do that again or use something like artifacts to pass information.
