### ISSUE TITLE
Permit Comments

### ISSUE THREAD

**Issue by hanej** [gocd-contrib/script-executor-task#9]
It seems Go doesn't like it when you put comments in the script executor.  Could you add support for comments?

**Comment by srinivasupadhya** [comment]
same as #7

**Comment by pracplayopen** [comment]
this is a feature, not a bug.  reason is gocd uses #{gocd-var-name} to designate a gocd-supplied script.

work-around is put two hashes together:
```
uname -a
## hello world --> gocd treats this as '# hello world'
uptime
```

this passes gocd script-checker and also outputs/runs as we would expect in the shell.
